// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetWeather():Promise<main.Weather>;

export function GetWeatherAt(arg1:number,arg2:number):Promise<main.Weather>;

export function ListPhotos():Promise<Array<string>>;
