// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChoosePhotosFolder() {
  return window['go']['main']['App']['ChoosePhotosFolder']();
}

export function GetWeather() {
  return window['go']['main']['App']['GetWeather']();
}

export function GetWeatherAt(arg1, arg2) {
  return window['go']['main']['App']['GetWeatherAt'](arg1, arg2);
}

export function ListPhotos() {
  return window['go']['main']['App']['ListPhotos']();
}
